services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  backend:
    build: .
    restart: on-failure
    command: bash -c "alembic upgrade head && python3 -m src.main"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    environment:
      - PG_HOST=postgres
